# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180824_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='任务执行结果')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host_to_remote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.HostToRemoteUser')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cmd', '批量命令'), ('file-transfer', '文件传输')], max_length=64)),
                ('content', models.CharField(max_length=255, verbose_name='任务内容')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tasks'),
        ),
    ]
