# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180826_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'initialized'), (1, 'success'), (2, 'failed'), (3, 'timeout')], default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='log_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'cmd'), (0, 'login'), (2, 'logout')], null=True),
        ),
    ]
